name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing compiler
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi
      - name: Installing python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Installing python dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing project
        run: |
          pip install pytest
          pytest -k TestTools -q ksboard_tools.py